---
version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ${REGION}
    IMAGE_REPO: ${APP_IMAGE_REPO}

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $IMAGE_REPO
      - IMAGE_TAG=$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} | cut -c 1-7)
  build:
    commands:
      - docker image build -t $APP_IMAGE_REPO:$IMAGE_TAG .
  post_build:
    commands:
      - docker image push $APP_IMAGE_REPO:$IMAGE_TAG
